### ISSUE TITLE
Problem with moment.js 

### ISSUE THREAD

**Issue by NYFB8888** [tomasrudh/analogclock#33] opened 2024-06-15 04:58 UTC
I wanted to install your analog clock card but I have a problem with the moment.js installation.
I followed the installation procedure as follows:
1)  created the ui-lovelace.yaml  file with the section 'resources'  with the following content 
  - url: https://unpkg.com/moment@2.29.1/min/moment-with-locales.js
    type: js
2) installed the card using the HACS installation method and the analog-clock is installed at /config/www/community/analogclock/analogclock.js.
3) added the new card using your example:

`views:`
 ` - type: custom:vertical-layout`
 `   cards:`
 `     - type: custom:analog-clock`
 `       hide_SecondHand: true`
 `       color_HourHand: '#326ba8'`
 `       color_MinuteHand: '#3273a8'`
 `       color_DigitalTime: '#CCCCCC'`
 `       color_FaceDigits: '#a83832'`
 `       hide_minorticks: true`
 `       timezone: America/Fortaleza`
 `       timezonedisplayname: UTC-3`
 `       dateformat: MMM Do YYYY`
 `       time format: hh mm`
``
4) restarted the HA service
and I am getting the following message 
"moment is not defined".

<img width="406" alt="image" src="https://github.com/tomasrudh/analogclock/assets/155231754/3a08d15a-c459-4eec-b389-f676f97b1ee5">

I am sure that HA service has access to https://unpkg.com/moment@2.29.1/min/moment-with-locales.js
I am using HA version 2023.6.1 
I cannot find any error in the log file (logger:   default: info
  logs:     custom_components.hacs: debug
    aiogithubapi: debug

Can you advice how to troubleshoot this problem or fix it?
NYFB

**Comment by tomasrudh** [comment] 2024-06-16 19:21
Try to clear the cache in your browser, sometimes you need to clear the cache and refresh the page a couple of times.

**Comment by NYFB8888** [comment] 2024-06-17 10:23
Many thanks for the prompt response. I followed your suggestion but without
success. The picture still shows the "moment is not defined" message.
I checked access to the moment's URL and curl downloaded it for me js
content.
The home assistant is new to me thus any suggestion on how to debug/trace
the analogclock.js would be very helpful for me.
Could you recommend to me a few tips?

**Comment by tomasrudh** [comment] 2024-06-24 20:08
Hi again, I am afraid I don't have many more ideas for you. There are at least two ways to clear the cache in the browser, ctrl-F5 and F12, Network tab and select 'Disable cache'. If that do not work I am not sure what to do.

**Comment by tomasrudh** [comment] 2024-07-14 08:25
I haven't heard back in a while, and I have no more ideas so I am closing this case.

**Comment by NYFB8888** [comment] 2024-07-16 02:31
Sorry, I was busy. None of your suggestions worked, so I gave up and installed another card.
Close the call.  Unfortunately for me the card does not work

**Comment by ardoviniandrea** [comment] 2024-07-26 13:42
I am having the same issue, also logging in incognito, which means it cannot be a cache issue.
If anyone has an idea I am happy to try it

**Comment by tomasrudh** [comment] 2024-07-26 19:44
Hi, I assume you see at least some of the clock, that indicates that Javascript works, and also that the main script is downloaded to your machine, but not moment.js, for some reason.

I don't know what browser you are using, but in Edge, press F12, and on the Network tab, check 'Disable cache', and press F5 at least two times.

If it still do not work, browse to this URL and verify that you see a quite long Javascript:
https://unpkg.com/moment@2.30.1/min/moment-with-locales.js

That would indicate you can access the moment.js file, but not being able to download it.

**Comment by tomasrudh** [comment] 2024-07-27 07:17
One more thing, have you restarted Home Assistant since you added the resource lines in ui-lovelace.yaml?

**Comment by ardoviniandrea** [comment] 2024-07-29 07:47
Apologies as I could have been much much more exaustive on my report.

Here's my yaml card:
```
type: custom:analog-clock
color_HourHand: '#326ba8'
color_MinuteHand: '#3273a8'
color_DigitalTime: '#CCCCCC'
color_FaceDigits: '#a83832'
hide_minorticks: true
timezone: America/Fortaleza
dateformat: MMM Do YYYY
timeformat: hh mm
```

I want to add that everthing works well untill I add to the yaml card
```
dateformat: MMM Do YYYY
timeformat: hh mm
```
I tried to add both single and double quote for the format, but everytime I save and close the editor the quotes get removed.


I have added moment.js in my Home Assistant resources and restarded HomeAssistant.

I do see a clock, but with the alert red icon on the top left, as you can see in the attached image
<img width="898" alt="Screenshot 2024-07-29 at 09 43 20" src="https://github.com/user-attachments/assets/6d3cc1ae-bf8c-4299-90cf-bd279fe8418f">

I am on Chrome and I did disable cache in the inspection console, but still no luck
Going to this link does load an extremely long javascript page
https://unpkg.com/moment@2.30.1/min/moment-with-locales.js

Is there anything else I can try?

**Comment by tomasrudh** [comment] 2024-07-29 08:16
Thanks for the report. I have tried your config and it works fine for me, also in Chrome.
![image](https://github.com/user-attachments/assets/d995c6d3-ad2b-4d19-9eda-e2f8b779c6e0)

So the problem is not your config, that is just fine.

I am sorry, I am out of ideas.

**Comment by tomasrudh** [comment] 2024-07-30 07:28
Good news! I have just released version 3.0, it eliminates the need for moment.js. Please try it out, I would appreciate if you could tell me how it goes.

**Comment by ardoviniandrea** [comment] 2024-07-30 16:35
Tested it on my side and it's not working correctly.

I am facing a different problem now, but I am opening a separate issue to keep things tidy.
Thanks for working on this release

**Comment by tomasrudh** [comment] 2024-07-30 19:26
I appreciate you opening a separate issue. Are you still having problem with Moment, or may I close this one?

**Comment by ardoviniandrea** [comment] 2024-07-30 20:33
Yes, this issue is resolved, the card loads correctly now

**Closed** 2024-07-31 20:58 UTC
