### ISSUE TITLE
moment not defined

### ISSUE THREAD

**Issue by IanAdd** [tomasrudh/analogclock#19] opened 2021-06-17 07:20 UTC
Copied and pasted one of your examples.

Used HACS to install

Added the extra resource reference mentioned
https://unpkg.com/moment@2.29.1/min/moment-with-locales.js

Restarted HA, using vanilla HA version 2021.6.2

'moment not defined' shows up in card with no hands

**Comment by tomasrudh** [comment] 2021-06-17 16:11
Hello, it might take more than one restart to get 'moment' to work. If that still not works, could you please share the part of your configuration file where you reference 'moment'.

Thanks,
Tomas

**Comment by IanAdd** [comment] 2021-06-20 09:20
Have restarted HA several times and also rebooted pi.
No difference.
So the resource reference was entered using the HA UI... on the page /config/lovelace/resources
My existing resource references are all local but I followed your instruction and entered both -
unpkg.com/moment@2.29.1/min/moment-with-locales.js
and 
https://unpkg.com/moment@2.29.1/min/moment-with-locales.js
in the url field.

**Comment by tomasrudh** [comment] 2021-06-20 19:48
Try to also clear the cache in your browser.

**Comment by IanAdd** [comment] 2021-06-20 23:11
Same problem in android app, two PCs, 4 browsers....

**Comment by tomasrudh** [comment] 2021-06-21 06:54
Ok, so the problem is likely not in the browser then. My instruction mention how to add 'moment' using the configuration.yaml file, unfortunately do I not have experience of configuring using UI.

If you have downloaded the file moment-with-locales.js to your server you should enter the path to that file. Download the file and place it in the same path as your other resources, and reference the 'moment' file as your other resources.

**Comment by tomasrudh** [comment] 2021-07-01 05:58
I am closing this, please get back if you still have problem.

**Closed by tomasrudh** 2021-07-01 05:58 UTC
